basePath: /api/v1
host: williamproject-backend-production.up.railway.app
info:
  contact: {}
  description: William Project API Documentation
  title: William Project API
  version: "1.0"
paths:
  /images:
    get:
      description: Mengambil semua gambar dari folder `images`
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lihat daftar gambar
      tags:
      - Images
  /images/{name}:
    delete:
      description: Menghapus gambar berdasarkan nama
      parameters:
      - description: Nama Gambar
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hapus gambar
      tags:
      - Images
    get:
      description: Mengambil gambar berdasarkan nama
      parameters:
      - description: Nama Gambar
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lihat satu gambar
      tags:
      - Images
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Mengunggah satu file gambar ke folder `images`
      parameters:
      - description: File Gambar
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload gambar
      tags:
      - Images
  /uploads:
    post:
      consumes:
      - multipart/form-data
      description: Mengunggah banyak gambar sekaligus ke folder `images`
      parameters:
      - description: Daftar File Gambar
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload banyak gambar
      tags:
      - Images
schemes:
- https
swagger: "2.0"
